services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - API_URL=http://server:8000

  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@rocketfrog.ai
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  db:
    hostname: db
    image: ankane/pgvector
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@rocketfrog.ai
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql